anfisa_for_friends/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('', views.Description.as_view(), name='description'),
]

anfisa_for_friends/anfisa_for_friends/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls')),
    path('about/', include('about.urls')),
    path('ice_cream/', include('ice_cream.urls')),
    path('contest/', include('contest.urls')),
    path('admin/', admin.site.urls),
]

anfisa_for_friends/contest/urls.py
from django.urls import path

from . import views

app_name = 'contest'

urlpatterns = [
    path('', views.proposal, name='create'),
    path('list/', views.proposal_list, name='list'),
    path('<int:pk>/edit/', views.proposal, name='edit'),
    path('<int:pk>/delete/', views.delete_proposal, name='delete'),
]

anfisa_for_friends/homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
]

anfisa_for_friends/ice_cream/urls.py
from django.urls import path

from . import views

app_name = 'ice_cream'

urlpatterns = [
    path('', views.ice_cream_list, name='ice_cream_list'),
    path('<int:pk>/', views.ice_cream_detail, name='ice_cream_detail'),
]

anfisa_for_friends/contest/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


class Contest(models.Model):
    title = models.CharField(verbose_name='Название', max_length=20)
    description = models.TextField(verbose_name='Описание')
    price = models.IntegerField(
        verbose_name='Цена',
        validators=[MinValueValidator(10), MaxValueValidator(100)],
        help_text='Рекомендованная розничная цена',
    )
    comment = models.TextField(verbose_name='Комментарий', blank=True)

anfisa_for_friends/core/models.py
from django.db import models


class PublishedModel(models.Model):
    """Абстрактная модель. Добвляет флаг is_published."""
    is_published = models.BooleanField(
        default=True,
        verbose_name='Опубликовано'
    )

    class Meta:
        abstract = True

anfisa_for_friends/ice_cream/models.py
from django.db import models

from core.models import PublishedModel


class Category(PublishedModel):
    title = models.CharField(max_length=256, verbose_name='Название')
    slug = models.SlugField(max_length=64, unique=True, verbose_name='Слаг')
    output_order = models.PositiveSmallIntegerField(
        default=100,
        verbose_name='Порядок отображения'
    )

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'Категории'
        ordering = ('output_order', )

    def __str__(self):
        return self.title


class Topping(PublishedModel):
    title = models.CharField(max_length=256, verbose_name='Название')
    slug = models.SlugField(max_length=64, unique=True, verbose_name='Слаг')

    class Meta:
        verbose_name = 'топпинг'
        verbose_name_plural = 'Топпинги'

    def __str__(self):
        return self.title


class Wrapper(PublishedModel):
    title = models.CharField(
        max_length=256,
        verbose_name='Название',
        help_text='Уникальное название обёртки, не более 256 символов'
    )

    class Meta:
        verbose_name = 'обёртка'
        verbose_name_plural = 'Обёртки'

    def __str__(self):
        return self.title


class IceCream(PublishedModel):
    title = models.CharField(max_length=256, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    wrapper = models.OneToOneField(
        Wrapper,
        on_delete=models.SET_NULL,
        related_name='ice_cream',
        null=True,
        blank=True,
        verbose_name='Обёртка'
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name='ice_creams',
        verbose_name='Категория'
    )
    output_order = models.PositiveSmallIntegerField(
        default=100,
        verbose_name='Порядок отображения'
    )
    toppings = models.ManyToManyField(Topping, verbose_name='Топпинги')
    is_on_main = models.BooleanField(default=False, verbose_name='На главную')
    price = models.DecimalField(max_digits=5, decimal_places=2)

    class Meta:
        verbose_name = 'мороженое'
        verbose_name_plural = 'Мороженое'
        # ordering = ('output_order', 'title')

    def __str__(self):
        return self.title

anfisa_for_friends/contest/forms.py
from django import forms

from .models import Contest


class ContestForm(forms.ModelForm):

    class Meta:
        model = Contest
        fields = '__all__'
        widgets = {
            'description': forms.Textarea({'cols': '22', 'rows': '5'}),
            'comment': forms.Textarea({'cols': '22', 'rows': '5'}),
        }

anfisa_for_friends/about/views.py
from django.views.generic import TemplateView

from contest.models import Contest


class Description(TemplateView):
    template_name = 'about/description.html'

    def get_context_data(self, **kwargs):
        # Получаем словарь контекста из родительского метода.
        context = super().get_context_data(**kwargs)
        # Добавляем в словарь ключ total_count;
        # значение ключа — число объектов модели Birthday.
        context['total_count'] = Contest.objects.count()
        # Возвращаем изменённый словарь контекста.
        return context

anfisa_for_friends/contest/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .forms import ContestForm
from .models import Contest


def proposal(request, pk=None):
    if pk is not None:
        instance = get_object_or_404(Contest, pk=pk)
    else:
        instance = None
    form = ContestForm(request.POST or None, instance=instance)
    context = {'form': form}
    if form.is_valid():
        form.save()
    return render(request, 'contest/form.html', context)


def delete_proposal(request, pk):
    instance = get_object_or_404(Contest, pk=pk)
    form = ContestForm(instance=instance)
    context = {'form': form}
    if request.method == 'POST':
        instance.delete()
        return redirect('contest:list')
    return render(request, 'contest/form.html', context)


def proposal_list(request):
    contest_proposals = Contest.objects.order_by('id')
    context = {'contest_proposals': contest_proposals}
    return render(request, 'contest/contest_list.html', context)

anfisa_for_friends/homepage/views.py
from django.shortcuts import render

from ice_cream.models import IceCream


def index(request):
    template_name = 'homepage/index.html'
    ice_cream_list = IceCream.objects.values('id', 'title', 'category__title')
    context = {'ice_cream_list': ice_cream_list}
    return render(request, template_name, context)

anfisa_for_friends/ice_cream/views.py
from django.shortcuts import get_object_or_404, render

from ice_cream.models import IceCream


def ice_cream_detail(request, pk):
    template_name = 'ice_cream/detail.html'
    ice_cream = get_object_or_404(
        IceCream.objects.filter(
            is_published=True,
            category__is_published=True
        ),
        pk=pk
    )
    context = {'ice_cream': ice_cream}
    return render(request, template_name, context)


def ice_cream_list(request):
    template = 'ice_cream/list.html'
    ice_cream_list = IceCream.objects.select_related('category').filter(
        is_published=True,
        category__is_published=True
    )

    context = {'ice_cream_list': ice_cream_list}
    return render(request, template, context)

anfisa_for_friends/templates/about/description.html
{% extends "base.html" %}
{% block title %}
  Анфиса для друзей. О проекте
{% endblock %}
{% block content %}
  <h1 class="pb-2 mb-0">О проекте</h1>
  <p>
    Каталог экзотических сортов мороженого.
  </p>
  <p>
    Мы проводим конкурс рецептов мороженого среди наших друзей.
  </p>
  <p>
    Количество поданных заявок: {{ total_count }}
  </p>
{% endblock %}

anfisa_for_friends/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    {% load static %}
    {% load django_bootstrap5 %}
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/fav.png' %}" type="image">
    {% bootstrap_css %}
    <title>
      {% block title %}{% endblock %}
    </title>
  </head>
  <body>
    {% include "includes/header.html" %}
    <main class="pt-5 my-5">
      <div class="container">
        {% block content %}{% endblock %}
      </div>
    </main>
    {% include "includes/footer.html" %}   
  </body>
  <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
</html>

anfisa_for_friends/templates/contest/contest_list.html
{% extends "base.html" %}

{% block title %}
  Список заявок
{% endblock %}

{% block content %}
  {% for proposal in contest_proposals %}
    <div>
      {{ proposal.id }}, {{ proposal.title }}, {{ proposal.price }},
      {{ proposal.description }}{% if proposal.comment %}, {{ proposal.comment }}{% endif %}
        <br>
      <a href="{% url 'contest:edit' proposal.id %}">Редактировать заявку</a>
      <a href="{% url 'contest:delete' proposal.id %}">Удалить заявку</a>
    </div>
  {% endfor %}
{% endblock %}

anfisa_for_friends/templates/contest/form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
  Конкурс рецептов мороженого
{% endblock %}

{% block content %}
  {% with data=form.instance %}
    {% if "/edit/" in request.path %}
      <h2>Редактировать заявку {{ data.pk }}</h2>
    {% elif "/delete/" in request.path %}
      <h2>Удалить заявку {{ data.pk }}</h2>
    {% else %}
      <h2>Подать заявку</h2>
    {% endif %}
    <div class="card col-4">
      <div class="card-header">
        Конкурс мороженого
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
            {% if not "/delete/" in request.path %}
                {% bootstrap_form form %}
            {% else %}
                <p>{{ data.title }}</p>
                <p>{{ data.price }}</p>
                <p>{{ data.description }}</p>
                <p>{% if data.comment %} {{ data.comment }}</p>
                {% endif %}
            {% endif %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
    {% if form.is_valid %}
        <h2>Рецепт мороженого {{ data.title }} принят на конкурс!</h2>
        <div>Номер заявки: {{ data.id }}</div>
    {% endif %}
  {% endwith %}
  <hr>
  <div>
    <a href="{% url 'contest:list' %}">Список всех заявок</a>
  </div>
{% endblock %}

anfisa_for_friends/templates/homepage/index.html
{% extends "base.html" %}
{% block title %}
  Анфиса для друзей. Главная
{% endblock %}
{% block content %}
  <h1 class="pb-2 mb-0">Главная страница</h1>
  <div class="row">
    {% for ice_cream in ice_cream_list %}
      {% include "includes/ice_cream_card.html" %}
    {% endfor %}
  </div>
{% endblock %}

anfisa_for_friends/templates/ice_cream/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Анфиса для друзей. Мороженое {{ ice_cream.title|lower }}
{% endblock %}
{% block content %}
  <h1 class="pb-2 mb-0">{{ ice_cream.title }}</h1>  
  <div class="row mt-3">
    <div class="col-12 col-md-6">
      <h2>Описание</h2>
      <p>{{ ice_cream.description }}</p>
      {% if ice_cream.wrapper %}
        <p>Обёртка: {{ ice_cream.wrapper.title }}</p>
      {% endif %}     
      <h4>
        <span class="badge bg-secondary">{{ ice_cream.category.title }}</span>
        <span class="badge bg-dark">{{ ice_cream.price }}</span>
      </h4>
      Топпинги:
      <ul class="list-group list-group-flush">
        {% for topping in ice_cream.toppings.all %}
          <li class="list-group-item">- {{ topping.title }}</li>
        {% endfor %}        
      </ul>
    </div> 
    <div class="col-12 col-md-6 mb-3">
      <img 
        class="img-fluid" 
        height="400" width="300"
        src="{% static 'img/image-holder.png' %}"
        >      
    </div>
  </div>     
{% endblock %}

anfisa_for_friends/templates/ice_cream/list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Анфиса для друзей. Список мороженого
{% endblock %}
{% block content %}
  <h1 class="pb-2 mb-0">Каталог мороженого</h1>
  <div class="row">
    {% for ice_cream in ice_cream_list %}
      {% ifchanged %}
        <div class="row mt-5" id="{{ ice_cream.category.slug }}">
          <div class="col-12">
            <h3>{{ ice_cream.category.title }}</h3>
          </div>
        </div>
      {% endifchanged %}
      {% include "includes/ice_cream_card.html" %}
    {% endfor %}
  </div>
{% endblock %}

anfisa_for_friends/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© «MyKit Corp»</p>
</footer>

anfisa_for_friends/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top shadow-sm">
    <div class="container">
      <div 
        class="navbar-toggler" 
        type="button" 
        data-toggle="collapse" 
        data-target="#navbarNav" 
        aria-controls="navbarNav" 
        aria-expanded="false" 
        aria-label="Toggle navigation"
        >
        <span class="navbar-toggler-icon"></span>
      </div>
      <div class="collapse navbar-collapse" id="navbarNav">
        {% with request.resolver_match.view_name as view_name %}            
        <ul class="nav nav-pills">
          <li class="nav-item">              
            <a
              class="nav-link {% if view_name == 'homepage:index' %} active {% endif %}" 
              href="{% url 'homepage:index' %}"
              >
              Главная 
            </a> 
          </li>
          <li class="nav-item">
            <a 
              class="nav-link {% if view_name == 'ice_cream:ice_cream_list' %} active {% endif %}" 
              href="{% url 'ice_cream:ice_cream_list' %}"
              >
              Каталог мороженого
            </a> 
          </li>
          <li class="nav-item">
            <a 
              class="nav-link {% if view_name == 'about:description' %} active {% endif %}"
              href="{% url 'about:description' %}"
            >
              О проекте
            </a> 
          </li>
          <li class="nav-item">
            <a
              class="nav-link {% if view_name == 'contest:create' %} active {% endif %}"
              href="{% url 'contest:create' %}"
            >
              Конкурс
            </a>
          </li>
        </ul>
        {% endwith %}
      </div> 
      <a class="navbar-brand" href="{% url 'homepage:index' %}">
        <img src="{% static 'img/logo.png' %}" height="50" class="d-inline-block align-top" alt="">            
      </a>         
    </div>
  </nav>
</header>

anfisa_for_friends/templates/includes/ice_cream_card.html
{% load static %}
<div class="col-6 col-md-4 my-1">
    <div class="card">
      <img 
        class="img-fluid card-img-top" 
        height="400" width="300"
        src="{% static 'img/image-holder.png' %}"
      >
      <div class="card-body">           
        <h5 class="card-title">{{ ice_cream.title }} </h5>
        <p class="badge bg-secondary">{{ ice_cream.price }}</p>
        <p class="card-text">{{ ice_cream.description|truncatechars:40 }}</p>
        <a class="mt-3 regular-link" href="{% url 'ice_cream:ice_cream_detail' ice_cream.id %}">
          Подробнее -->
        </a>
      </div>
    </div>
  </div>